name: 'Add Integration'

on:
  workflow_dispatch:
    inputs:
      name:
        type: 'string'
        required: true
        description: 'name'

      git_repository_url:
        type: 'string'
        required: true
        description: 'Git Repository URL'

      documentation_url:
        type: 'string'
        required: false
        description: 'Documentation URL (optional)'

jobs:
  main:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'actions/setup-node@v2'
        with:
          node-version: 16

      - run: 'npm ci'

      - run: 'node ./src/add-integration.mjs'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
          INTEGRATION_NAME: '${{ github.event.inputs.name }}'
          INTEGRATION_DOCUMENTATION_URL: '${{ github.event.inputs.documentation_url }}'
          INTEGRATION_GIT_REPOSITORY_URL: '${{ github.event.inputs.git_repository_url }}'
