name: 'Remove Integration'

on:
  workflow_dispatch:
    inputs:
      id:
        type: 'string'
        required: true
        description: 'Integration ID'

jobs:
  main:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'actions/setup-node@v2'
        with:
          node-version: 16

      - run: 'npm ci'

      - run: 'node ./src/remove-integration.mjs'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
          INTEGRATION_ID: '${{ github.event.inputs.id }}'
